[project]
name = "hoardgui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "nicegui>=3.7.1",
    "requests>=2.32.5",
]
