[project]
name = "hoardgui"
version = "1.1.1"
description = "Simple Web UI for controlling lights set up wit HyperHDR"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "nicegui>=3.7.1",
    "requests>=2.32.5",
]
